# Site settings
title: ""
author: "Qile Chen"
description: ""
keywords: ""
biography: ""
colophon: ""

baseurl: ""
url: "http://hugosereno.eu"

twitter_username: ferreira_hugo
github_username: cqile
linkedin_username: hugoserenoferreira
facebook_username: hugo.sereno.ferreira
google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
